name: github-webhooks

services:
  app:
    build: .
    container_name: app
    ports:
      - "8888:8888"
    env_file: apps/server/.env.local
    environment:
      REDIS_HOST: redis
    volumes:
      - ./apps/server/private-key.pem:/usr/private-key.pem
    depends_on:
      redis:
        condition: service_started
