name: workflows

services:
  app:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: workflows-server
    ports:
      - "8888:8888"
    env_file: apps/server/.env.local
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
      MONGO_HOST: mongo
      STARTUP_CHECKS: "false"
    volumes:
      - ./apps/server/private-key.pem:/usr/private-key.pem
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_started
