name: Analyze
on:
  push:
    branches: ["[0-9]+.[0-9]+.[0-9x]+"]

env:
  CI: true

concurrency:
  group: {{ var 'github.workflow' }}-{{ var 'github.ref' }}
  cancel-in-progress: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
              
      {{> java }}


      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: {{ var 'runner.os' }}-sonar
          restore-keys: {{ var 'runner.os' }}-sonar

      - name: Build & Analyze
        run: ./gradlew build check sonar
        env:
          SONAR_TOKEN: {{ var 'secrets.SONAR_TOKEN' }}
          SONAR_HOST_URL: {{ var 'secrets.SONAR_HOST_URL' }}
