name: Test

on:
   workflow_dispatch:
    inputs:
      upload:
        description: "Upload Artifact"
        default: false
        required: true
        type: boolean

   pull_request:
      types: [opened, synchronize]
{{#unless sonar}}
   push:
      branches: ["[0-9]+.[0-9]+.[0-9x]+"]
{{/unless }}

env:
   CI: true

concurrency:
   group: {{ var 'github.workflow' }}-{{ var 'github.ref' }}
   cancel-in-progress: true

jobs:
   test:
      runs-on: ubuntu-latest
      timeout-minutes: 20
      permissions:
         contents: read
      steps:
         - name: Checkout
           uses: actions/checkout@v4
              
         {{> java }}


         - name: Build
           run: ./gradlew build check

         - uses: actions/upload-artifact@v4
           with:
              name: build
              path: "**/build/libs/*.jar"