name: Release
on:
   {{#if (eq upload.strategy "release") }}
   release:
      types: [published]
   {{else if (eq upload.strategy "push") }}
   push:
      branches: 
         - "main"
         - "main/**"
   {{/if}}

env:
   CI: true

{{#if (eq upload.strategy "push") }}
concurrency:
  group: {{ var 'github.workflow' }}-{{ var 'github.ref' }}
  cancel-in-progress: true
{{/if}}

jobs:
   build:
      runs-on: ubuntu-latest
      timeout-minutes: 20
      permissions:
         contents: read
         {{#if upload.github}}
         packages: write
         {{else}}
         packages: read
         {{/if}}
      steps:
         - uses: actions/checkout@v4
           with:
              lfs: true
              
         {{> java }}


         - name: Build and upload
           run: ./gradlew build upload
           env:
              {{#if upload.modrinth}}
              MODRINTH_TOKEN: {{ var 'secrets.MODRINTH_TOKEN' }}
              {{/if}}
              {{#if upload.curseforge}}
              CURSEFORGE_TOKEN: {{ var 'secrets.CURSEFORGE_TOKEN' }}
              {{/if}}
              {{#if (eq upload.strategy "release")}}
              CHANGELOG: {{ var 'github.event.release.body' }}
              RELEASE_VERSION: {{ var 'github.event.release.tag_name' }}
              {{/if}}
              {{#if (eq upload.strategy "push") }}
              CHANGELOG: automated patch release
              PATCH_VERSION: {{ var 'github.run_number' }}
              {{/if}}
              {{#if upload.github}}
              GITHUB_TOKEN: {{ var 'secrets.GITHUB_TOKEN' }}
              {{/if}}
              {{#if upload.nexus}}
              NEXUS_USER: {{ var 'secrets.NEXUS_USER' }}
              NEXUS_TOKEN: {{ var 'secrets.NEXUS_TOKEN' }}
              {{/if}}

         - name: Publish Release Metadata
           uses: actions/upload-artifact@v7
           with:
              archive: false
              path: build/release.json
              retention-days: 1
