name: Test

on:
   workflow_dispatch:
   
   pull_request:
      types: [opened, synchronize]

   push:
      branches: 
         - "main"
         - "main/**"

env:
  CI: true

concurrency:
  group: {{ var 'github.workflow' }}-{{ var 'github.ref' }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
              
      {{> java }}
           dependency-graph: generate-and-submit


      {{#if sonar}}
      - name: Cache SonarQube packages
        if: {{ var 'github.event_name != \'pull_request\'' }}
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: {{ var 'runner.os' }}-sonar
          restore-keys: {{ var 'runner.os' }}-sonar
      {{/if}}

      {{#if upload.snapshots}}
      - uses: PssbleTrngle/find-release@v1
        id: draft
        with:
          type: draft
          token: {{ var 'secrets.GITHUB_TOKEN' }}
      {{/if}}

      - name: Test
        run: ./gradlew build check --stacktrace
      {{#if upload.snapshots}}
        env:
          RELEASE_VERSION: {{ var 'steps.action.outputs.tag' }}
      {{/if}}

      {{#if sonar}}
      - name: Analyze
        if: {{ var 'github.event_name != \'pull_request\'' }}
        run: ./gradlew sonar
        continue-on-error: true
        env:
          SONAR_TOKEN: {{ var 'secrets.SONAR_TOKEN' }}
          SONAR_HOST_URL: {{ var 'secrets.SONAR_HOST_URL' }}
          GITHUB_DEPENDENCY_GRAPH_ENABLED: false
      {{/if}}

      {{#if upload.snapshots}}
      - name: Publish -SNAPSHOT version
        if: {{ var 'github.event_name != \'pull_request\' && fromJSON(steps.draft.outputs.matched)' }}
        run: ./gradlew publish
        continue-on-error: true
        env:
          {{#if upload.nexus}}
          NEXUS_USER: {{ var 'secrets.NEXUS_USER' }}
          NEXUS_TOKEN: {{ var 'secrets.NEXUS_TOKEN' }}
          {{/if}}
          RELEASE_VERSION: {{ var 'steps.draft.outputs.tag' }}
          SNAPSHOT: true
      {{/if}}