name: Test

on:
   workflow_dispatch:
    inputs:
      upload:
        description: "Upload Artifact"
        default: false
        required: true
        type: boolean
   
   pull_request:
      types: [opened, synchronize]

   push:
      branches: 
         - "main"
         - "main/**"

env:
  CI: true

concurrency:
  group: {{ var 'github.workflow' }}-{{ var 'github.ref' }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
              
      {{> java }}
           dependency-graph: generate-and-submit


      {{#if sonar}}
      - name: Cache SonarQube packages
        if: {{ var 'github.event_name == \'push\'' }}
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: {{ var 'runner.os' }}-sonar
          restore-keys: {{ var 'runner.os' }}-sonar
      {{/if}}

      - name: Test
        run: ./gradlew build check

      {{#if sonar}}
      - name: Analyze
        if: {{ var 'github.event_name == \'push\'' }}
        run: ./gradlew sonar
        env:
          SONAR_TOKEN: {{ var 'secrets.SONAR_TOKEN' }}
          SONAR_HOST_URL: {{ var 'secrets.SONAR_HOST_URL' }}
          GITHUB_DEPENDENCY_GRAPH_ENABLED: false
      {{/if}}

      - uses: actions/upload-artifact@v4
        if: {{ var 'inputs.upload' }}
        with:
          name: build
          path: "**/build/libs/*.jar"