{{#if (multiple loaders.length)}}
{{#each loaders as |loader|}}     
{{ loader }}:
  - "/^{{ loader }}$/m" 
{{/each}}
{{/if}}

{{#if (multiple versions.length)}}
{{#each versions as |version|}}       
{{ version }}.x:
  - "/^{{ version }}$/m" 
{{/each}}
{{/if}}