name: Trigger Prerelease

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
  actions: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: PssbleTrngle/find-release@v1
        if: {{ var 'github.event_name != \'pull_request\'' }}
        id: action
        with:
          type: draft
          token: {{ var 'secrets.GITHUB_TOKEN' }}

      - uses: benc-uk/workflow-dispatch@v1
        if: toJson(steps.action.outputs.matched)
        with:
          workflow: release.yml
          inputs: '{ "rc": true, "version": "{{ var 'steps.action.outputs.tag' }}-rc.{{ var 'github.run_number' }}" }'
