{{#if (multiple loaders.length)}}
{{#each loaders as |loader|}}     
{{ loader }}:
  - "{{ loader }}" 
{{/each}}
{{/if}}

{{#if (multiple versions.length)}}
{{#each versions as |version|}}       
{{ version }}.x:
  - "{{ version }}" 
{{/each}}
{{/if}}