name: Publish Docker Images

on:
   workflow_dispatch:
   push:
      branches: [main]
   release:
      types: [published]

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

env:
   REGISTRY: ghcr.io
   GITHUB_REPO: ${{ github.repository }}

jobs:
   docker:
      strategy:
         matrix:
            app: [server, consumer, alarmer]
      permissions:
         contents: read
         packages: write

      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v6

         - name: Log in to the Container registry
           uses: docker/login-action@v4
           with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

         - name: Extract metadata (tags, labels) for Docker
           id: meta
           uses: docker/metadata-action@v5
           with:
              images: ${{ env.REGISTRY }}/${{ env.GITHUB_REPO }}-${{ matrix.app }}
              tags: |
                 type=raw,value=latest
                 type=raw,value=stable,enable=${{ github.event_name == 'release' }}
                 type=semver,pattern={{version}},enable=${{ github.event_name == 'release' }}
                 type=sha,priority=250,enable=${{ github.event_name != 'release' }}

         - name: Setup Bun
           uses: oven-sh/setup-bun@v2

         - name: Update release properties
           run: bun run packages/scripts/prerelease.ts
           env:
              BUILD_NUMBER: ${{ github.run_number }}

         - name: Build and push Docker image
           uses: docker/build-push-action@v6
           with:
              context: .
              file: apps/${{ matrix.app }}/Dockerfile
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
